language: node_js
node_js:
  - "stable"
before_install:
  - npm conf set strict-ssl false
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install
script:
  - npm run mae
  - npm run test
  - npm run report
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
notifications:
  email: false
