language: node_js
node_js:
  - "stable"
before_install:
  - npm conf set strict-ssl false
before_script:
  - phantomjs --version
  - npm install
script:
  - npm run instrument
  - npm run test-compile
  - npm run test-phantomjs
  - npm run coverage-report
after_script:
  - cat coverage/lcov.info | codeclimate
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
